import 'package:flutter/material.dart';

import 'package:fangeul/presentation/theme/palette_pack.dart';

/// 수동 디자인된 팔레트팩 레지스트리.
///
/// 10개 팔레트 (무료 4 + 프리미엄 6).
/// 각 팔레트는 surface 계열에 고유 색조를 반영하여
/// 앱 전체에 색상이 스며드는 효과를 낸다.
abstract final class PaletteRegistry {
  /// 기본 팔레트 ID.
  static const defaultId = 'midnight';

  // ──────────────────────────────────────────────
  // FREE 팔레트 (4개)
  // ──────────────────────────────────────────────

  /// 미드나잇 — 기본 틸+네이비 테마 (FangeulColors 토큰 기반).
  static const _midnight = PalettePack(
    id: 'midnight',
    nameKey: 'paletteMidnight',
    isPremium: false,
    previewColor: Color(0xFF4ECDC4),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF4ECDC4),
      onPrimary: Color(0xFF003735),
      primaryContainer: Color(0xFF1A3A38),
      onPrimaryContainer: Color(0xFF70F7ED),
      secondary: Color(0xFFFFE66D),
      onSecondary: Color(0xFF3E3700),
      secondaryContainer: Color(0xFF4A4200),
      onSecondaryContainer: Color(0xFFFFEFA0),
      tertiary: Color(0xFFFF6B6B),
      onTertiary: Color(0xFF680003),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF1E1E2E),
      onSurface: Color(0xFFE8E8F0),
      onSurfaceVariant: Color(0xFFA0A0B8),
      surfaceContainerLowest: Color(0xFF0F0F1A),
      surfaceContainerLow: Color(0xFF181828),
      surfaceContainer: Color(0xFF282840),
      surfaceContainerHigh: Color(0xFF323250),
      surfaceContainerHighest: Color(0xFF3C3C5A),
      outline: Color(0xFF4A4A60),
      outlineVariant: Color(0xFF353550),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF0F766E),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD4F5F2),
      onPrimaryContainer: Color(0xFF00201E),
      secondary: Color(0xFFB45309),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDDB3),
      onSecondaryContainer: Color(0xFF3A1C00),
      tertiary: Color(0xFFC62828),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF1E1E2E),
      onSurfaceVariant: Color(0xFF5A5A70),
      surfaceContainerLowest: Color(0xFFFAFAFE),
      surfaceContainerLow: Color(0xFFF5F5FB),
      surfaceContainer: Color(0xFFF0F0F8),
      surfaceContainerHigh: Color(0xFFE8E8F0),
      surfaceContainerHighest: Color(0xFFE0E0EC),
      outline: Color(0xFFB0B0C0),
      outlineVariant: Color(0xFFD8D8E4),
    ),
  );

  /// 퍼플 드림 — 콘서트 퍼플 테마.
  static const _purpleDream = PalettePack(
    id: 'purple_dream',
    nameKey: 'palettePurpleDream',
    isPremium: false,
    previewColor: Color(0xFFBB86FC),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFBB86FC),
      onPrimary: Color(0xFF380059),
      primaryContainer: Color(0xFF4F0080),
      onPrimaryContainer: Color(0xFFE8CCFF),
      secondary: Color(0xFFCDBFD6),
      onSecondary: Color(0xFF342B3C),
      secondaryContainer: Color(0xFF4B4253),
      onSecondaryContainer: Color(0xFFEADBF2),
      tertiary: Color(0xFFF0B7C8),
      onTertiary: Color(0xFF4A2533),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF1E1A2E),
      onSurface: Color(0xFFE8E4F0),
      onSurfaceVariant: Color(0xFFA8A0B8),
      surfaceContainerLowest: Color(0xFF120E1E),
      surfaceContainerLow: Color(0xFF1A1628),
      surfaceContainer: Color(0xFF282240),
      surfaceContainerHigh: Color(0xFF322C4E),
      surfaceContainerHighest: Color(0xFF3D365A),
      outline: Color(0xFF524A68),
      outlineVariant: Color(0xFF3A3350),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF6200EE),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE8D5FF),
      onPrimaryContainer: Color(0xFF22005D),
      secondary: Color(0xFF635B6B),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFEADBF2),
      onSecondaryContainer: Color(0xFF1F1826),
      tertiary: Color(0xFF7E4D5E),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1E1A24),
      onSurfaceVariant: Color(0xFF5A5468),
      surfaceContainerLowest: Color(0xFFFCF8FE),
      surfaceContainerLow: Color(0xFFF7F2FA),
      surfaceContainer: Color(0xFFF2ECF8),
      surfaceContainerHigh: Color(0xFFECE6F2),
      surfaceContainerHighest: Color(0xFFE6E0EC),
      outline: Color(0xFFB0A8C0),
      outlineVariant: Color(0xFFD8D0E4),
    ),
  );

  /// 오션 블루 — 시원한 블루 테마.
  static const _oceanBlue = PalettePack(
    id: 'ocean_blue',
    nameKey: 'paletteOceanBlue',
    isPremium: false,
    previewColor: Color(0xFF4FC3F7),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF4FC3F7),
      onPrimary: Color(0xFF003549),
      primaryContainer: Color(0xFF004D68),
      onPrimaryContainer: Color(0xFFC2E8FF),
      secondary: Color(0xFFB4CAD6),
      onSecondary: Color(0xFF1F333D),
      secondaryContainer: Color(0xFF354A54),
      onSecondaryContainer: Color(0xFFD0E6F2),
      tertiary: Color(0xFFC4C0EA),
      onTertiary: Color(0xFF2D2B4E),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF161C2E),
      onSurface: Color(0xFFE2E8F0),
      onSurfaceVariant: Color(0xFF98A8B8),
      surfaceContainerLowest: Color(0xFF0E121E),
      surfaceContainerLow: Color(0xFF121828),
      surfaceContainer: Color(0xFF1E2840),
      surfaceContainerHigh: Color(0xFF28334E),
      surfaceContainerHighest: Color(0xFF323E5A),
      outline: Color(0xFF4A5A6A),
      outlineVariant: Color(0xFF303E50),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF0277BD),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD0ECFF),
      onPrimaryContainer: Color(0xFF001E30),
      secondary: Color(0xFF4E616C),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD0E6F2),
      onSecondaryContainer: Color(0xFF0A1E28),
      tertiary: Color(0xFF5B5887),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFAFCFF),
      onSurface: Color(0xFF161C24),
      onSurfaceVariant: Color(0xFF4A5868),
      surfaceContainerLowest: Color(0xFFF6F9FE),
      surfaceContainerLow: Color(0xFFF0F5FB),
      surfaceContainer: Color(0xFFEAF0F8),
      surfaceContainerHigh: Color(0xFFE2EAF2),
      surfaceContainerHighest: Color(0xFFDCE4EC),
      outline: Color(0xFFA0B0C0),
      outlineVariant: Color(0xFFCCD8E4),
    ),
  );

  /// 로즈 골드 — 따뜻한 핑크 테마.
  static const _roseGold = PalettePack(
    id: 'rose_gold',
    nameKey: 'paletteRoseGold',
    isPremium: false,
    previewColor: Color(0xFFF48FB1),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF48FB1),
      onPrimary: Color(0xFF4E1130),
      primaryContainer: Color(0xFF6A2846),
      onPrimaryContainer: Color(0xFFFFD9E6),
      secondary: Color(0xFFD6BFC6),
      onSecondary: Color(0xFF3B2A30),
      secondaryContainer: Color(0xFF524047),
      onSecondaryContainer: Color(0xFFF3DCE2),
      tertiary: Color(0xFFEFBD94),
      onTertiary: Color(0xFF47290A),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF2E1A22),
      onSurface: Color(0xFFF0E4E8),
      onSurfaceVariant: Color(0xFFB8A0A8),
      surfaceContainerLowest: Color(0xFF200E16),
      surfaceContainerLow: Color(0xFF28141C),
      surfaceContainer: Color(0xFF3A222C),
      surfaceContainerHigh: Color(0xFF462C38),
      surfaceContainerHighest: Color(0xFF523844),
      outline: Color(0xFF6A4A58),
      outlineVariant: Color(0xFF4A3440),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFC2185B),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD9E6),
      onPrimaryContainer: Color(0xFF3E001D),
      secondary: Color(0xFF6B565B),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF3DCE2),
      onSecondaryContainer: Color(0xFF241419),
      tertiary: Color(0xFF7C5635),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFF8F9),
      onSurface: Color(0xFF241419),
      onSurfaceVariant: Color(0xFF68505A),
      surfaceContainerLowest: Color(0xFFFFF5F7),
      surfaceContainerLow: Color(0xFFFFF0F3),
      surfaceContainer: Color(0xFFFCE8ED),
      surfaceContainerHigh: Color(0xFFF6E0E6),
      surfaceContainerHighest: Color(0xFFF0D8E0),
      outline: Color(0xFFC0A0AA),
      outlineVariant: Color(0xFFE0CCD4),
    ),
  );

  // ──────────────────────────────────────────────
  // PREMIUM 팔레트 (6개)
  // ──────────────────────────────────────────────

  /// 콘서트 앙코르 — 골드+레드 무대 조명 테마.
  static const _concertEncore = PalettePack(
    id: 'concert_encore',
    nameKey: 'paletteConcertEncore',
    isPremium: true,
    previewColor: Color(0xFFFFD54F),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFD54F),
      onPrimary: Color(0xFF3E2E00),
      primaryContainer: Color(0xFF5A4300),
      onPrimaryContainer: Color(0xFFFFE99B),
      secondary: Color(0xFFFF8A80),
      onSecondary: Color(0xFF5C1410),
      secondaryContainer: Color(0xFF732A24),
      onSecondaryContainer: Color(0xFFFFDAD6),
      tertiary: Color(0xFFFFCC80),
      onTertiary: Color(0xFF452B00),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF2A2218),
      onSurface: Color(0xFFF0E8D8),
      onSurfaceVariant: Color(0xFFB8AE98),
      surfaceContainerLowest: Color(0xFF1C160E),
      surfaceContainerLow: Color(0xFF221C12),
      surfaceContainer: Color(0xFF342C1E),
      surfaceContainerHigh: Color(0xFF3E3628),
      surfaceContainerHighest: Color(0xFF4A4032),
      outline: Color(0xFF5E5444),
      outlineVariant: Color(0xFF423A2C),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFFF6F00),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFE0B2),
      onPrimaryContainer: Color(0xFF2E1500),
      secondary: Color(0xFFC62828),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD6),
      onSecondaryContainer: Color(0xFF410002),
      tertiary: Color(0xFF8D6A00),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFBF5),
      onSurface: Color(0xFF221C12),
      onSurfaceVariant: Color(0xFF655C4A),
      surfaceContainerLowest: Color(0xFFFFF9F3),
      surfaceContainerLow: Color(0xFFFFF5EC),
      surfaceContainer: Color(0xFFFAEEDE),
      surfaceContainerHigh: Color(0xFFF4E6D4),
      surfaceContainerHighest: Color(0xFFEEDECA),
      outline: Color(0xFFC0B098),
      outlineVariant: Color(0xFFE0D4C0),
    ),
  );

  /// 골든 아워 — 석양 앰버 테마.
  static const _goldenHour = PalettePack(
    id: 'golden_hour',
    nameKey: 'paletteGoldenHour',
    isPremium: true,
    previewColor: Color(0xFFFFAB40),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFAB40),
      onPrimary: Color(0xFF482900),
      primaryContainer: Color(0xFF663C00),
      onPrimaryContainer: Color(0xFFFFDCB8),
      secondary: Color(0xFFDEC0A0),
      onSecondary: Color(0xFF3F2C15),
      secondaryContainer: Color(0xFF57422A),
      onSecondaryContainer: Color(0xFFFBDCBA),
      tertiary: Color(0xFFC8CA8C),
      onTertiary: Color(0xFF313208),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF2A2016),
      onSurface: Color(0xFFF0E4D6),
      onSurfaceVariant: Color(0xFFB8A894),
      surfaceContainerLowest: Color(0xFF1E160E),
      surfaceContainerLow: Color(0xFF241C12),
      surfaceContainer: Color(0xFF342A1C),
      surfaceContainerHigh: Color(0xFF3E3426),
      surfaceContainerHighest: Color(0xFF4A3E30),
      outline: Color(0xFF605440),
      outlineVariant: Color(0xFF443A2A),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFE65100),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDCB8),
      onPrimaryContainer: Color(0xFF2A1600),
      secondary: Color(0xFF705940),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFBDCBA),
      onSecondaryContainer: Color(0xFF281806),
      tertiary: Color(0xFF576322),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFBF6),
      onSurface: Color(0xFF221A10),
      onSurfaceVariant: Color(0xFF685C48),
      surfaceContainerLowest: Color(0xFFFFF9F2),
      surfaceContainerLow: Color(0xFFFFF4E8),
      surfaceContainer: Color(0xFFFAEDD8),
      surfaceContainerHigh: Color(0xFFF4E5CC),
      surfaceContainerHighest: Color(0xFFEEDDC2),
      outline: Color(0xFFC0AE94),
      outlineVariant: Color(0xFFE0D2BC),
    ),
  );

  /// 체리 블로썸 — 봄 파스텔 핑크 테마.
  static const _cherryBlossom = PalettePack(
    id: 'cherry_blossom',
    nameKey: 'paletteCherryBlossom',
    isPremium: true,
    previewColor: Color(0xFFF8BBD0),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF8BBD0),
      onPrimary: Color(0xFF4E2038),
      primaryContainer: Color(0xFF69364E),
      onPrimaryContainer: Color(0xFFFFD9EA),
      secondary: Color(0xFFD6BFCA),
      onSecondary: Color(0xFF3B2A32),
      secondaryContainer: Color(0xFF524049),
      onSecondaryContainer: Color(0xFFF3DCE5),
      tertiary: Color(0xFFDCC094),
      onTertiary: Color(0xFF3E2D0E),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF2A1C24),
      onSurface: Color(0xFFF0E4EA),
      onSurfaceVariant: Color(0xFFB8A0AE),
      surfaceContainerLowest: Color(0xFF1E1018),
      surfaceContainerLow: Color(0xFF24161E),
      surfaceContainer: Color(0xFF36242E),
      surfaceContainerHigh: Color(0xFF422E3A),
      surfaceContainerHighest: Color(0xFF4E3A46),
      outline: Color(0xFF6A5060),
      outlineVariant: Color(0xFF4A3442),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFD81B60),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD9EA),
      onPrimaryContainer: Color(0xFF3E001D),
      secondary: Color(0xFF6C5660),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF3DCE5),
      onSecondaryContainer: Color(0xFF261620),
      tertiary: Color(0xFF7A5A2D),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFF8F9),
      onSurface: Color(0xFF24161C),
      onSurfaceVariant: Color(0xFF685058),
      surfaceContainerLowest: Color(0xFFFFF5F7),
      surfaceContainerLow: Color(0xFFFFF0F4),
      surfaceContainer: Color(0xFFFCE6ED),
      surfaceContainerHigh: Color(0xFFF6DEE6),
      surfaceContainerHighest: Color(0xFFF0D6E0),
      outline: Color(0xFFC0A0AC),
      outlineVariant: Color(0xFFE0CCD6),
    ),
  );

  /// 네온 나잇 — 사이버펑크 그린+퍼플 테마.
  static const _neonNight = PalettePack(
    id: 'neon_night',
    nameKey: 'paletteNeonNight',
    isPremium: true,
    previewColor: Color(0xFF76FF03),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF76FF03),
      onPrimary: Color(0xFF0A3800),
      primaryContainer: Color(0xFF145000),
      onPrimaryContainer: Color(0xFFA8FF6A),
      secondary: Color(0xFFCE93D8),
      onSecondary: Color(0xFF3A1B42),
      secondaryContainer: Color(0xFF52325A),
      onSecondaryContainer: Color(0xFFEBBCF4),
      tertiary: Color(0xFF40E0D0),
      onTertiary: Color(0xFF00312C),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF141E18),
      onSurface: Color(0xFFDEF0E4),
      onSurfaceVariant: Color(0xFF98B8A4),
      surfaceContainerLowest: Color(0xFF0C140E),
      surfaceContainerLow: Color(0xFF101A14),
      surfaceContainer: Color(0xFF1C2E22),
      surfaceContainerHigh: Color(0xFF26382C),
      surfaceContainerHighest: Color(0xFF304238),
      outline: Color(0xFF4A6254),
      outlineVariant: Color(0xFF2E4436),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF2E7D32),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD0F5D2),
      onPrimaryContainer: Color(0xFF002106),
      secondary: Color(0xFF7B1FA2),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF0D4FC),
      onSecondaryContainer: Color(0xFF2A0036),
      tertiary: Color(0xFF00695C),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFF6FFF6),
      onSurface: Color(0xFF101E14),
      onSurfaceVariant: Color(0xFF445A4C),
      surfaceContainerLowest: Color(0xFFF2FBF2),
      surfaceContainerLow: Color(0xFFECF8EC),
      surfaceContainer: Color(0xFFE4F2E6),
      surfaceContainerHigh: Color(0xFFDCECDE),
      surfaceContainerHighest: Color(0xFFD4E4D6),
      outline: Color(0xFF96B09C),
      outlineVariant: Color(0xFFC8DCC8),
    ),
  );

  /// 민트 브리즈 — 상쾌한 민트 테마.
  static const _mintBreeze = PalettePack(
    id: 'mint_breeze',
    nameKey: 'paletteMintBreeze',
    isPremium: true,
    previewColor: Color(0xFF80CBC4),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF80CBC4),
      onPrimary: Color(0xFF00352F),
      primaryContainer: Color(0xFF004D45),
      onPrimaryContainer: Color(0xFFA8F0E8),
      secondary: Color(0xFFB1CCC7),
      onSecondary: Color(0xFF1C3530),
      secondaryContainer: Color(0xFF324B47),
      onSecondaryContainer: Color(0xFFCDE8E3),
      tertiary: Color(0xFFADC6E0),
      onTertiary: Color(0xFF163048),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF162826),
      onSurface: Color(0xFFE0F0EC),
      onSurfaceVariant: Color(0xFF94B4AE),
      surfaceContainerLowest: Color(0xFF0E1C1A),
      surfaceContainerLow: Color(0xFF122220),
      surfaceContainer: Color(0xFF1E3432),
      surfaceContainerHigh: Color(0xFF283E3C),
      surfaceContainerHighest: Color(0xFF324A48),
      outline: Color(0xFF4A6A64),
      outlineVariant: Color(0xFF2E4A44),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF00695C),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFC8F5EC),
      onPrimaryContainer: Color(0xFF00201B),
      secondary: Color(0xFF4A635E),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFCDE8E3),
      onSecondaryContainer: Color(0xFF06201C),
      tertiary: Color(0xFF3E5F7D),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFF6FFFB),
      onSurface: Color(0xFF122220),
      onSurfaceVariant: Color(0xFF445C58),
      surfaceContainerLowest: Color(0xFFF2FBF8),
      surfaceContainerLow: Color(0xFFECF8F4),
      surfaceContainer: Color(0xFFE4F2ED),
      surfaceContainerHigh: Color(0xFFDCECE6),
      surfaceContainerHighest: Color(0xFFD4E4DE),
      outline: Color(0xFF90B0A8),
      outlineVariant: Color(0xFFC4DCD6),
    ),
  );

  /// 선셋 카페 — 생일 카페 따뜻한 테마.
  static const _sunsetCafe = PalettePack(
    id: 'sunset_cafe',
    nameKey: 'paletteSunsetCafe',
    isPremium: true,
    previewColor: Color(0xFFFFCC80),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFCC80),
      onPrimary: Color(0xFF462A00),
      primaryContainer: Color(0xFF643E00),
      onPrimaryContainer: Color(0xFFFFE2B8),
      secondary: Color(0xFFDAC0A4),
      onSecondary: Color(0xFF3D2C18),
      secondaryContainer: Color(0xFF55422C),
      onSecondaryContainer: Color(0xFFF8DCBE),
      tertiary: Color(0xFFC8C694),
      onTertiary: Color(0xFF31300C),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      surface: Color(0xFF2A2018),
      onSurface: Color(0xFFF0E6D8),
      onSurfaceVariant: Color(0xFFB8AC98),
      surfaceContainerLowest: Color(0xFF1E160E),
      surfaceContainerLow: Color(0xFF241C12),
      surfaceContainer: Color(0xFF362A1E),
      surfaceContainerHigh: Color(0xFF403428),
      surfaceContainerHighest: Color(0xFF4C3E32),
      outline: Color(0xFF625644),
      outlineVariant: Color(0xFF443C2C),
    ),
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFBF360C),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFE2B8),
      onPrimaryContainer: Color(0xFF2C1500),
      secondary: Color(0xFF6E5B42),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF8DCBE),
      onSecondaryContainer: Color(0xFF271906),
      tertiary: Color(0xFF596225),
      onTertiary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFBF5),
      onSurface: Color(0xFF221A10),
      onSurfaceVariant: Color(0xFF685C48),
      surfaceContainerLowest: Color(0xFFFFF9F0),
      surfaceContainerLow: Color(0xFFFFF4E6),
      surfaceContainer: Color(0xFFFCECD8),
      surfaceContainerHigh: Color(0xFFF6E4CC),
      surfaceContainerHighest: Color(0xFFF0DCC2),
      outline: Color(0xFFC0AE94),
      outlineVariant: Color(0xFFE0D2BC),
    ),
  );

  /// 전체 팔레트 목록 (무료 우선 정렬).
  static const all = <PalettePack>[
    _midnight,
    _purpleDream,
    _oceanBlue,
    _roseGold,
    _concertEncore,
    _goldenHour,
    _cherryBlossom,
    _neonNight,
    _mintBreeze,
    _sunsetCafe,
  ];

  /// 무료 팔레트만.
  static List<PalettePack> get free => all.where((p) => !p.isPremium).toList();

  /// 프리미엄 팔레트만.
  static List<PalettePack> get premium =>
      all.where((p) => p.isPremium).toList();

  /// [id]에 해당하는 팔레트를 반환한다.
  ///
  /// 존재하지 않는 ID가 전달되면 [ArgumentError]를 던진다.
  static PalettePack get(String id) {
    return all.firstWhere(
      (p) => p.id == id,
      orElse: () => throw ArgumentError('Unknown palette: $id'),
    );
  }
}
